trigger:
- master

pr: none

variables:
  ACR.ContainerRegistryServiceConnnection: 'codecampster-nebbia-registry'
  DockerHub.ContainerRegistryServiceConnnection: 'orlando-codecamp-registry'

stages:
- stage: Build
  displayName: Build and Push
  jobs:  
  - job: build_legacy
    displayName: Build and Push Legacy
    pool:
      image: 'ubuntu-latest'
    variables: 
      App.Name: mvc
      App.Dockerfile: src/Web/WebMVC/Dockerfile
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: $(ACR.ContainerRegistryServiceConnnection)
        repository: codecampster/$(App.Name)
        buildContext: .
        Dockerfile: $(App.Dockerfile)
        tags: |
          $(Build.BuildNumber)
          latest
  - job: build_greenfield
    displayName: Build and Push Greenfield
    pool:
      image: 'ubuntu-latest'
    variables: 
      App.Dockerfile: src/Web/CodeCampster.Web/Dockerfile
      DockerHub.OrganizationName: orlandocodecamp
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: $(DockerHub.ContainerRegistryServiceConnnection)
        repository: $(DockerHub.OrganizationName)/codecampster
        buildContext: .
        Dockerfile: $(App.Dockerfile)
        tags: |
          $(Build.BuildNumber)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'orlando-codecamp-registry'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'