FROM microsoft/dotnet:3.0-sdk
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["Web/WebStatus/WebStatus.csproj", "Web/WebStatus/"]

RUN dotnet restore "Web/WebStatus/WebStatus.csproj"
COPY . .
WORKDIR "/src/Web/WebStatus"
RUN dotnet build --no-restore "WebStatus.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]